web/Models/Plant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace web.Models
{
    public class Plant
    {
        public int PlantID { get; set; }
        public string Name { get; set; }
        // Show this text when there is no entry.
        [DisplayFormat(NullDisplayText = "No description")]
#nullable enable
        public string? Description { get; set; }
        [DisplayFormat(NullDisplayText = "No note")]
        public string? Note { get; set; }
        public byte[]? image { get; set; }
#nullable disable
        [Display(Name = "Days between watering")]
        [Range(typeof(int), "1", "100")]
        public int DaysBetweenWatering { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Last watering date")]
        public DateTime LastWateredDate { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Next watering date")]
        public DateTime NextWateredDate { get; set; }

        [DisplayFormat(NullDisplayText = "No category")]

#nullable enable
        public Category? Category { get; set; }
#nullable disable
        public int CategoryID { get; set; }

        [DisplayFormat(NullDisplayText = "No location")]

#nullable enable
        public Location? Location { get; set; }
#nullable disable
        public int LocationID { get; set; }
        

        public User User { get; set; }

        

    }
}

web/Controllers/PlantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.IO;

namespace web.Controllers
{
    // Require login for everything	
    [Authorize(AuthenticationSchemes = "Identity.Application" )]
    public class PlantsController : Controller
    {
        private readonly PileaContext _context;

        // Object for fetching user info.	
        private readonly UserManager<User> _usermanager;

        public PlantsController(PileaContext context, UserManager<User> userManager)
        {
            _context = context;
            _usermanager = userManager;
        }

        // GET: Plants
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {

            //             Get current user.
            var currentUser = await _usermanager.GetUserAsync(User);

            // define sort parameters
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DaysBetweenWateringParm"] = sortOrder == "DaysBetweenWatering" ? "DaysBetweenWatering_desc" : "DaysBetweenWatering";
            ViewData["LastWateredDateParm"] = sortOrder == "LastWateredDate" ? "LastWateredDate_desc" : "LastWateredDate";
            ViewData["NextWateredDateParm"] = sortOrder == "NextWateredDate" ? "NextWateredDate_desc" : "NextWateredDate";
            ViewData["CategoryParm"] = sortOrder == "Category" ? "Category_desc" : "Category";
            ViewData["LocationParm"] = sortOrder == "Location" ? "Location_desc" : "Location";

            // define search parameters
            ViewData["CurrentFilter"] = searchString;


            // Query
            var plants = from p in _context.Plants.Where(p => p.User == currentUser).Include(p => p.Category).Include(p => p.Location) select p;


            // search
            if (!String.IsNullOrEmpty(searchString))
            {
                plants = plants.Where(p => p.Name.Contains(searchString)
                                        || p.Description.Contains(searchString)
                                        || p.Note.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    plants = plants.OrderByDescending(p => p.Name);
                    break;
                case "DaysBetweenWatering":
                    plants = plants.OrderBy(p => p.DaysBetweenWatering);
                    break;
                case "DaysBetweenWatering_desc":
                    plants = plants.OrderByDescending(p => p.DaysBetweenWatering);
                    break;
                case "LastWateredDate":
                    plants = plants.OrderBy(p => p.LastWateredDate);
                    break;
                case "LastWateredDate_desc":
                    plants = plants.OrderByDescending(p => p.LastWateredDate);
                    break;
                case "NextWateredDateParm":
                    plants = plants.OrderBy(p => p.NextWateredDate);
                    break;
                case "NextWateredDateParm_desc":
                    plants = plants.OrderByDescending(p => p.NextWateredDate);
                    break;
                case "Category":
                    plants = plants.OrderBy(p => p.Category);
                    break;
                case "Category_desc":
                    plants = plants.OrderByDescending(p => p.Category);
                    break;
                case "Location":
                    plants = plants.OrderBy(p => p.Location);
                    break;
                case "Location_desc":
                    plants = plants.OrderByDescending(p => p.Location);
                    break;
                default:
                    plants = plants.OrderBy(p => p.Name);
                    break;
            }
            return View(await plants.AsNoTracking().ToListAsync());


        }

        // GET: Plants/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var currentUser = await _usermanager.GetUserAsync(User);
            if (id == null)
            {
                return NotFound();
            }

            var plant = await _context.Plants
                .Include(p => p.Category)
                .Include(p => p.Location)
                .Where(p => p.User == currentUser)
                .FirstOrDefaultAsync(m => m.PlantID == id);
            if (plant == null)
            {
                return NotFound();
            }

            return View(plant);
        }

        // GET: Plants/Create
        public IActionResult Create()
        {
            var currentUserID = _usermanager.GetUserId(User);
            ViewData["CategoryID"] = new SelectList(_context.Categories.Where(c => c.User.Id == currentUserID), "CategoryID", "PlantCategory");
            ViewData["LocationID"] = new SelectList(_context.Locations.Where(l => l.User.Id == currentUserID), "LocationID", "Name");
            return View();
        }

        // POST: Plants/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlantID,Name,Description,Note,image,DaysBetweenWatering,LastWateredDate,CategoryID,LocationID")] Plant plant)
        {

            // Get ApplicationUser object (plant owner)	
            var currentUser = await _usermanager.GetUserAsync(User);
            var pileaContext = _context.Plants.Where(p => p.User == currentUser).Include(p => p.Category).Include(p => p.Location);
            if (ModelState.IsValid)
            {
                plant.User = currentUser;
                plant.image = UploadImage(Request);

                plant.NextWateredDate = plant.LastWateredDate.AddDays(plant.DaysBetweenWatering);

                // Save and redirect
                _context.Update(plant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryID", plant.CategoryID);
            ViewData["LocationID"] = new SelectList(_context.Locations.Where(l => l.User == currentUser), "LocationID", "LocationID", plant.LocationID);
            return View(plant);
        }



        // GET: Plants/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            // Get ApplicationUser object (plant owner)	
            var currentUser = await _usermanager.GetUserAsync(User);
            if (id == null)
            {
                return NotFound();
            }

            var plant = await _context.Plants.FindAsync(id);
            if (plant == null || plant.User != currentUser)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "PlantCategory", plant.CategoryID);
            ViewData["LocationID"] = new SelectList(_context.Locations.Where(l => l.User == currentUser), "LocationID", "Name", plant.LocationID);
            return View(plant);
        }

        // POST: Plants/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PlantID,Name,Description,Note,image,DaysBetweenWatering,LastWateredDate,CategoryID,LocationID")] Plant plant)
        {
            if (id != plant.PlantID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    plant.image = UploadImage(Request);
                    plant.NextWateredDate = plant.LastWateredDate.AddDays(plant.DaysBetweenWatering);
                    _context.Update(plant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlantExists(plant.PlantID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "CategoryID", "CategoryID", plant.CategoryID);
            ViewData["LocationID"] = new SelectList(_context.Locations, "LocationID", "LocationID", plant.LocationID);
            return View(plant);
        }

        // GET: Plants/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var currentUser = await _usermanager.GetUserAsync(User);

            var plant = await _context.Plants
                .Include(p => p.Category)
                .Include(p => p.Location)
                .FirstOrDefaultAsync(m => m.PlantID == id && m.User == currentUser);
            if (plant == null)
            {
                return NotFound();
            }

            return View(plant);
        }

        // POST: Plants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

web/Views/Plants/Create.cshtml
@model web.Models.Plant

@{
    ViewData["Title"] = "Create";
}

<h1>Add new plant</h1>

<hr />

    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class ="row">
        <div class="form-group col-md-5">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        </div>

        <div class ="row">
            <div class="form-group col-md-5">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
        </div>

        <div class ="row">
            <div class="form-group col-md-5" >
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group col-md-5">
                <label asp-for="DaysBetweenWatering" class="control-label"></label>
                <input asp-for="DaysBetweenWatering" class="form-control" min="1"/>
                <span asp-validation-for="DaysBetweenWatering" class="text-danger"></span>
            </div>
        </div>


        <div class ="row">
            <div class="form-group col-md-5">
                <label asp-for="LastWateredDate" class="control-label"></label>
                <input type="date" id="LastWateredDatePickerCreate" asp-for="LastWateredDate" class="form-control" />
                @* <input asp-for="LastWateredDate" class="form-control" /> *@
                <span asp-validation-for="LastWateredDate" class="text-danger"></span>
            </div>
            @* <div class="form-group col-md-5">
                <label asp-for="NextWateredDate" class="control-label"></label>
                <input asp-for="NextWateredDate" class="form-control" />
                <span asp-validation-for="NextWateredDate" class="text-danger"></span>
            </div> *@
            <div class="form-group col-md-5">
                <label class="control-label">Image</label>                
                <input asp-for="image" type="file" class="form-control" id="file1" name="file1" multiple="multiple" />
                <span asp-validation-for="image" class="text-danger"></span>
            </div>
        </div>

        <div class ="row">
            <div class="form-group col-md-5">
                <label asp-for="Category" class="control-label"></label>
                <select asp-for="CategoryID" class ="form-control" asp-items="ViewBag.CategoryID"></select>
            </div>
            <div class="form-group col-md-5">
                <label asp-for="Location" class="control-label"></label>
                <select asp-for="LocationID" class ="form-control" asp-items="ViewBag.LocationID"></select>
            </div>
        </div>

        @* <div class ="row">
            
        </div> *@
            
          
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn " />
            </div>
        </form>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>







<script>
    LastWateredDatePickerCreate.max = new Date().toISOString().split("T")[0];
</script>

web/Views/Plants/Delete.cshtml
@model web.Models.Plant

@{
    ViewData["Title"] = "Delete";
}

<br>
<h3>Are you sure you want to delete this plant?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Category.PlantCategory)
        </dd class>
        <dt class = "col-sm-3">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-9">
            @Html.DisplayFor(model => model.Location.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PlantID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

web/Views/Plants/Details.cshtml
@model web.Models.Plant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<h4>Plant</h4>
<h4>@Model.image</h4>
<div>
    <div style="float: right; ">
        <div class="card">
            @if (!(@Model.image == null))
            {
                <div style="width: 330px; height: 330px; background-position: center; background-repeat: no-repeat;
                                                background-size: cover; background-image:
                                                url(data:image/jpg;base64,@Convert.ToBase64String(@Model.image));">
                </div>
            }
            else
            {
                <div style='width: 330px; height: 330px; background-position: center; background-repeat: no-repeat;
                                    background-size: cover; background-image: url("../../plant.jpg")'></div>
            }


            <div class="card-body">
                <h4>@Html.DisplayFor(model => model.Name)</h4>
            </div>
        </div>
    </div>

    <hr />
    <dl class="row">
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <!--
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.image)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.image)
        </dd>-->
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.DaysBetweenWatering)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.DaysBetweenWatering)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.LastWateredDate)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.LastWateredDate)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.NextWateredDate)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.NextWateredDate)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Category.PlantCategory)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.Location.Name)
        </dd>
    </dl>
</div>


<div>
    <a asp-action="Edit" asp-route-id="@Model.PlantID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

web/Views/Plants/Edit.cshtml
@model web.Models.Plant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Plant</h4>
<hr />

<form asp-action="Edit" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PlantID" />

    <div class ="row">
        <div class="form-group col-md-5">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class ="row">
        <div class="form-group col-md-5">
            <label asp-for="Description" class="control-label"></label>
            <textarea asp-for="Description" class="form-control" ></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>


    <div class ="row">
        <div class="form-group col-md-5">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
        </div>
        <div class="form-group col-md-5">
                <label asp-for="DaysBetweenWatering" class="control-label"></label>
                <input asp-for="DaysBetweenWatering" class="form-control" min="1"/>
                <span asp-validation-for="DaysBetweenWatering" class="text-danger"></span>
        </div>
    </div>


    <div class ="row">
        <div class="form-group col-md-5">
            <label asp-for="LastWateredDate" class="control-label"></label>
            <input type="date" id="LastWateredDatePickerEdit" asp-for="LastWateredDate" class="form-control" />
            @* <input asp-for="LastWateredDate" class="form-control" /> *@
            <span asp-validation-for="LastWateredDate" class="text-danger"></span>
        </div>
        @* <div class="form-group col-md-5">
            <label asp-for="NextWateredDate" class="control-label"></label>
            <input asp-for="NextWateredDate" class="form-control" />
            <span asp-validation-for="NextWateredDate" class="text-danger"></span>
        </div> *@
        <div class="form-group col-md-5">
            <label class="control-label">Image</label>
            <input asp-for="image" type="file" class="form-control" id="file1" name="file1" multiple="multiple" />
            <span asp-validation-for="image" class="text-danger"></span>
        </div>
    </div>


    <div class ="row">
        <div class="form-group col-md-5">
            <label asp-for="Category" class="control-label"></label>
            <select asp-for="CategoryID" class="form-control" asp-items="ViewBag.CategoryID"></select>
            <span asp-validation-for="CategoryID" class="text-danger"></span>
        </div>
        <div class="form-group col-md-5">
            <label asp-for="Location" class="control-label"></label>
            <select asp-for="LocationID" class="form-control" asp-items="ViewBag.LocationID" ></select>
            <span asp-validation-for="LocationID" class="text-danger"></span>
        </div>
    </div>

    @* <div class ="row">
        
    </div> *@

            <div class="form-group">
                <input type="submit" value="Save" class="btn" />
            </div>
           
        </form>
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </div>
</div>



<script>
    LastWateredDatePickerEdit.max = new Date().toISOString().split("T")[0];
</script>

web/Views/Plants/Index.cshtml
@model IEnumerable<web.Models.Plant>

@{

    ViewData["Title"] = "Index";
}


<h1>My plants</h1>



<br>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
            <button class="add_field_button btn btn-success btn-md float-right"><a asp-action="Create"
                    style="text-decoration: none;">Add new plant</a></button>

        </p>
    </div>
</form>

<div class="card-columns">




    @foreach (var item in Model)







    {
        <div class="card">
            <a asp-action="Details" asp-route-id="@item.PlantID">
                @if (item.image != null)







                {
                    <div class="card-img"
                        style="background-image: url(data:image/jpg;base64,@Convert.ToBase64String(item.image));">
                    </div>

                }



                else



                {
                    <div asp-action="Details" asp-route-id="@item.PlantID" class="card-img"
                        style='background-image: url("plant.jpg")'></div>

                }
            </a>
            <div class="card-body">
                <button type="button" class="close" aria-label="Close">
                    <a asp-action="Delete" asp-route-id="@item.PlantID" style="text-decoration: none;">x</a>
                </button>

                <h5 class="card-title">@item.Name</h5>
                <h6 class="card-subtitle mb-2 text-muted">@item.Note</h6>

                <p class="card-text">@item.Description</p>
                <br>
                @if (item.NextWateredDate < DateTime.Now)































































































































































































































































































































































































































































































































                {
                    <p class="card-text" style="color:red">Next watering @item.NextWateredDate.ToShortDateString()</p>

                }































































































































































































































































































































































































































































































































                else































































































































































































































































































































































































































































































































                {
                    <p class="card-text">Next watering @item.NextWateredDate.ToShortDateString()</p>

                }
                @* Form for watering flowers *@
                @using (Html.BeginForm("WaterPlant", "Plants", new { id = item.PlantID }))































































































































































































































































































































































































































































































































                {
                    @Html.AntiForgeryToken()

                    <button type="submit" class="btn" value="water">Water</button>

                }



                <a asp-action="Edit" asp-route-id="@item.PlantID" class="float-right">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                    </svg>
                </a>


            </div>



        </div>

    }

</div>